=== Guzele/Web-homework/Semester2/XMLT-001/part2.dtd
<!--author: Garifullina Guzel
    task link  https://kodaktor.ru/g/xml_intro
-->

        <!ELEMENT myPortfolio (myCompetencies)>
        <!ELEMENT myCompetencies (competency)*>
        <!ELEMENT competency EMPTY>
        <!ATTLIST competency in CDATA #REQUIRED>
        <!ATTLIST competency value CDATA #REQUIRED>

=== Guzele/Web-homework/Semester2/1_XMLT-001/part2_my_portfolio.xml
<?xml version="1.0" encoding="utf-8"?>
<!--author: Garifullina Guzel-->
<!-- task link  https://kodaktor.ru/g/xml_intro-->
<!DOCTYPE myPortfolio SYSTEM "part2.dtd">

<myPortfolio>
    <myCompetencies>
        <competency in="HTML" value="Intermediate"/>
        <competency in="CSS" value="Intermediate"/>
        <competency in="Javascript" value="Beginner"/>
        <competency in="MVC ASP.NET" value="Proficient"/>
        <competency in="MS SQL" value="Proficient"/>
        <competency in="MongoDb" value="Proficient"/>
    </myCompetencies>
</myPortfolio>
